### ISSUE TITLE
마 공부안하나??

### ISSUE THREAD

**Issue by moto6** [YoungsikPark/stm32_F767#1]
마 삼대 몇드는데?? 으잉?

공부 안하냐 이말이야

요오오오오ㅗㅗㅗㅗㅗㅗㅗㅗㅗㅗㅗㅗ즘 것들은 남산 7분도 못찍으면서 말이야 으잉

백준으로 따라와

**Comment by YoungsikPark** [comment]
bootloader 개발중임 ^^

**Comment by moto6** [comment]
오~ 붓로더~~~  와유ㅜㅜㅜㅜ~ 싸운즈 라잌 뻐킹 인터레스팅
